### ISSUE TITLE
bug: please remove any unnecessary quoting/escaping

### ISSUE THREAD

**Issue by ronaldpetty** [dumindarw/kafka-oauthbearer-keycloak#5]
First, great job on demo app.

Second, was updating it to use Keycloak past version 22. If you changed the image to 23.0.7 or higher, you get this error.

```
kafka-oauthbearer-keycloak % docker logs kafka-oauthbearer-keycloak-keycloak-dev-1
Option: '--import-realm --health-enabled' is not expected to contain whitespace, please remove any unnecessary quoting/escaping
Possible solutions: --import-realm
```

A similar issue appeared here https://github.com/keycloak/keycloak/issues/31413.

A workaround for me is updating the docker-compose.yml as follows:

```
  keycloak-dev:
    image: quay.io/keycloak/keycloak:23.0.7 #19.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    #command: [
    #  "start-dev",
    #  "--import-realm --health-enabled=true --metrics-enabled=true"
    #]
    command: "start-dev --import-realm --health-enabled=true --metrics-enabled=true"
```

I am guessing some issue with "joining" the array components starting in 23+. I didn't look that deep. If I do, I'll send an update.
